name: Build Vial Firmware

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Vial Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: vial-kb/vial-qmk
      qmk_ref: vial
      preparation_command: |
        cp -rf keyboards/* qmk_firmware/keyboards/

  publish:
    name: 'Publish Firmware Artifacts'
    if: always() && !cancelled()
    needs: build
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@main
